Settings:
  command: cratesadmin
  aliases: []
  permission: 'crates.admin'
  permission-message: '&cVocê não possui permissão para executar esse comando!'

Messages:
  command-usage:
    - ''
    - '&cComandos disponíveis:'
    - ''
    - ' &c/{cmd} key/give <jogador> <crate> <quantia>'
    - ' &c/{cmd} set <crate>'
    - ' &c/{cmd} remove'
    - ''
  null-block: '&cVocê precisa estar olhando para um bloco!'
  null-crate: '&cVocê precisa estar olhando para uma crate!'
  invalid-crate: '&cEssa crate não existe!'
  invalid-amount: '&cA quantia informada é inválida!'
  existing-crate: '&cJá existe uma crate nesse local!'
  offline-player: '&cEsse jogador está offline!'
  need-key: '&cVocê precisa estar segurando a chave dessa caixa!'
  need-space: '&cA abertura da caixa foi cancelada por falta de espaço no inventário!'
<<<<<<< HEAD
  give-all: '&7Você recebeu &f{amount}x {key}&7! &8(Giveall)'
=======
>>>>>>> 3b71325d45999be59b70484b7c31cb0745c4ba98

Titles:
  reward:
    title: ''
    subtitle: '{item}'