name: Crates
description: Only a simple crates plugin.
version: 1.0
api-version: 1.16
author: zPedroo_
main: com.zpedroo.voltzcrates.VoltzCrates
depend: [HolographicDisplays, ProtocolLib]
load: POSTWORLD